services:
  # ----------------------------------------------------
  # PostgreSQL DATABASE (main service)
  # ----------------------------------------------------
  postgres:
    image: postgres:17
    #container_name: drental-docker
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ai_rental_db
    ports:
      - "5450:5432"
    volumes:
      - drental_pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d # <--- FIXED
    restart: always

  # ----------------------------------------------------
  # ANALYTICS SERVICE (Python environment in Docker)
  # ----------------------------------------------------
  analytics:
    build:
      context: .
      dockerfile: Dockerfile
    #container_name: drental-analytics
    depends_on:
      - postgres
    volumes:
      - .:/app
    ports:
      - "8888:8888" # expose Jupyter Notebook
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/ai_rental_db
      RUNNING_IN_DOCKER: "1"

    # command: >
    #   jupyter notebook
    #   --ip=0.0.0.0
    #   --port=8888
    #   --no-browser
    #   --allow-root

volumes:
  drental_pgdata:
